"""Coder 节点：根据 Plan 和用户需求使用 DeepSeek API 生成可执行的 Python 代码。

所有生成的代码必须满足：
- 包含所有必要的 import
- 假设数据文件在 ./data/ 目录下（相对路径）
- 使用 print() 展示输出
- 不包含 os.system / subprocess / eval / exec 等危险调用
"""

import hashlib
import os
import re
import textwrap

from loguru import logger

from src.agent.state import AgentState
from src.agent.nodes.prompts.loader import load_prompt
from src.agent.nodes.prompts.coder_user import build_coder_user_message
# Dangerous pattern check
# ---------------------------------------------------------------------------

_DANGEROUS_PATTERNS = [
    "os.system",
    "subprocess",
    "eval(",
    "exec(",
    "__import__",
]


def _has_dangerous_code(code: str) -> bool:
    """检查代码是否包含危险模式。

    Args:
        code: 生成的 Python 代码

    Returns:
        如果发现危险模式则返回 True
    """
    return any(pattern in code for pattern in _DANGEROUS_PATTERNS)


# ---------------------------------------------------------------------------
# Code extraction from LLM response
# ---------------------------------------------------------------------------


def _extract_code_block(content: str) -> str:
    """从 LLM 响应中提取 Python 代码块。

    优先匹配 ```python ... ``` 格式，
    其次匹配 ``` ... ```（无语言标记），
    最后回退为原始内容。

    Args:
        content: LLM 原始响应文本

    Returns:
        提取出的纯 Python 代码字符串
    """
    # 匹配带语言标记的代码块
    match = re.search(r"```python\s*\n(.*?)```", content, re.DOTALL)
    if match:
        return match.group(1).strip()

    # 匹配无语言标记的代码块
    match = re.search(r"```\s*\n(.*?)```", content, re.DOTALL)
    if match:
        return match.group(1).strip()

    # 回退：直接返回原始内容（去除首尾空白）
    return content.strip()


# ---------------------------------------------------------------------------
# LLM-based code generation
# ---------------------------------------------------------------------------


def _generate_code_with_llm(
    plan: list[str],
    query: str,
    workspace: str,
) -> str:
    """使用 DeepSeek API 生成 Python 代码。

    Args:
        plan: 执行计划步骤列表
        query: 用户原始自然语言需求
        workspace: 工作区绝对路径（仅用于上下文，不硬编码到代码中）

    Returns:
        生成的 Python 代码字符串

    Raises:
        ValueError: 当环境变量 DEEPSEEK_API_KEY 未设置时
    """
    api_key = os.environ.get("DEEPSEEK_API_KEY")
    if not api_key:
        raise ValueError("环境变量 DEEPSEEK_API_KEY 未设置")

    from langchain_deepseek import ChatDeepSeek

    llm = ChatDeepSeek(
        model="deepseek-chat",
        api_key=api_key,
        temperature=0.3,
    )

    messages = [
        {"role": "system", "content": load_prompt("coder.md")},
        {"role": "user", "content": build_coder_user_message(query, plan)},
    ]

    response = llm.invoke(messages)
    content = response.content.strip()

    return _extract_code_block(content)


# ---------------------------------------------------------------------------
# Fallback code generation (safe mode)
# ---------------------------------------------------------------------------


def _generate_fallback_code(
    plan: list[str],
    query: str,
    workspace: str,
    error: str | None = None,
) -> str:
    """当 LLM 调用失败或计划异常时，生成安全的回退代码。

    回退代码不会尝试执行任何有意义的分析，
    而是打印错误信息并正常退出，避免崩溃。

    Args:
        plan: 执行计划（可能为空或包含错误信息）
        query: 用户原始需求
        workspace: 工作区路径
        error: 可选的错误描述

    Returns:
        安全的回退 Python 代码
    """
    error_note = f"生成错误: {error}" if error else "未能生成有效代码"
    query_safe = query if (query and query.strip()) else "用户未提供需求"

    lines = [
        "#!/usr/bin/env python3",
        "# Auto-generated by DecisionCoder (fallback)",
        f"# {error_note}",
        f"# 需求: {query_safe}",
        "# 执行计划:",
    ]

    if plan:
        for i, step in enumerate(plan, 1):
            lines.append(f"#   {i}. {step}")
    else:
        lines.append("#   (无有效执行计划)")

    lines.append("")

    # 用纯字符串拼接避免 f-string 中大括号转义混乱
    body = textwrap.dedent("""\
    import sys

    def main():
        print("=" * 60)
        print("DecisionCoder 执行报告 (安全模式)")
        print("=" * 60)
        print()

        query = {query_safe!r}
        plan = {plan_repr!r}

        print(f"原始需求: {{query}}")
        print()

        if plan:
            print("原执行计划:")
            for idx, step in enumerate(plan, 1):
                print(f"  {{idx}}. {{step}}")
        else:
            print("提示: 未能生成有效的执行计划。")
            print("请检查: 1) 需求是否清晰  2) 数据文件是否存在  3) API Key 是否有效")

        print()
        print("结束 (无有效代码可执行)")
        return 0

    if __name__ == "__main__":
        sys.exit(main())
    """)

    # 安全地插入变量值
    body = body.replace("{query_safe!r}", repr(query_safe))
    body = body.replace("{plan_repr!r}", repr(plan))

    return "\n".join(lines) + body


# ---------------------------------------------------------------------------
# Main node entry point
# ---------------------------------------------------------------------------


def coder_node(state: AgentState) -> dict:
    """根据用户需求和执行计划生成可执行的 Python 代码。

    输入: state["user_query"], state["plan"], state["workspace_path"]
    输出: {"generated_code": "完整 Python 代码字符串"}

    如果人在回路提供了 AI_FIX 开头的修复代码，则直接使用。

    Args:
        state: 当前 AgentState

    Returns:
        包含 generated_code 字段的 partial state
    """
    # ---- 人在回路：AI 修复的代码直接使用 ----
    human_feedback = state.get("human_feedback")

    # ---- 入口日志 ----
    query = state.get("user_query", "")
    code_len = len(state.get("generated_code", ""))
    logger.info(
        "[Coder] 进入节点 | user_query={!r} | plan_steps={} | code_len={} | human_feedback={!r}",
        query[:50],
        len(state.get("plan", [])),
        code_len,
        (human_feedback or "")[:50],
    )

    if human_feedback and human_feedback.startswith("AI_FIX:"):
        logger.info("[Coder] 检测到 AI_FIX 反馈，直接使用修复代码")
        code = human_feedback[len("AI_FIX:"):].strip()
        logger.info(
            "[Coder] 退出节点（AI_FIX 路径） | code_len={} | hash={}",
            len(code),
            hashlib.md5(code.encode()).hexdigest()[:8],
        )
        return {"generated_code": code, "human_feedback": None}

    # ---- 获取输入 ----
    plan = state.get("plan", [])
    query = state.get("user_query", "")
    workspace = state.get("workspace_path", ".")

    # ---- 边界情况：计划为空或包含错误 ----
    if not plan or any(str(p).startswith("错误") for p in plan):
        code = _generate_fallback_code(plan, query, workspace)
        logger.warning("[Coder] 计划为空或包含错误，使用回退代码 | code_len={}", len(code))
        logger.info(
            "[Coder] 退出节点（回退路径） | code_len={} | hash={}",
            len(code),
            hashlib.md5(code.encode()).hexdigest()[:8],
        )
        return {"generated_code": code}

    # ---- 边界情况：用户需求为空 ----
    if not query or not query.strip():
        code = _generate_fallback_code(plan, "", workspace, error="用户需求为空")
        logger.warning("[Coder] 用户需求为空，使用回退代码 | code_len={}", len(code))
        logger.info(
            "[Coder] 退出节点（回退路径） | code_len={} | hash={}",
            len(code),
            hashlib.md5(code.encode()).hexdigest()[:8],
        )
        return {"generated_code": code}

    # ---- 正常路径：使用 DeepSeek LLM 生成代码 ----
    try:
        code = _generate_code_with_llm(plan, query, workspace)
    except Exception as exc:
        logger.error("[Coder] LLM 生成失败 | type={} | message={}", type(exc).__name__, exc)
        code = _generate_fallback_code(plan, query, workspace, error=str(exc))
        logger.info(
            "[Coder] 退出节点（异常回退） | code_len={} | hash={}",
            len(code),
            hashlib.md5(code.encode()).hexdigest()[:8],
        )
        return {"generated_code": code}

    # ---- 后置安全检查 ----
    if _has_dangerous_code(code):
        logger.warning("[Coder] 代码包含危险调用，已拦截 | code_len={}", len(code))
        code = _generate_fallback_code(
            plan, query, workspace, error="LLM 生成代码包含危险调用，已拦截"
        )
        logger.info(
            "[Coder] 退出节点（安全拦截） | code_len={} | hash={}",
            len(code),
            hashlib.md5(code.encode()).hexdigest()[:8],
        )
        return {"generated_code": code}

    # ---- 出口日志 ----
    logger.info(
        "[Coder] 退出节点（正常） | code_len={} | hash={}",
        len(code),
        hashlib.md5(code.encode()).hexdigest()[:8],
    )

    return {"generated_code": code}


# 别名，兼容 graph.py / Task 7 的 run(state) 约定
run = coder_node
