"""Coder 节点：根据 Plan 生成可执行的 Python 代码。"""

import textwrap

from src.agent.state import AgentState


def coder_node(state: AgentState) -> dict:
    """根据 Plan 和上下文生成 Python 代码。

    当前 Week 1 版本使用模板化生成，
    后续可替换为 LLM 调用（读取 src/agent/prompts/coder.md）。

    Args:
        state: 当前 AgentState

    Returns:
        包含 generated_code 字段的 partial state
    """
    plan = state["plan"]
    query = state["user_query"]
    workspace = state["workspace_path"]
    human_feedback = state.get("human_feedback")

    # 如果人在回路提供了 AI 修复的代码，直接使用
    if human_feedback and human_feedback.startswith("AI_FIX:"):
        code = human_feedback[len("AI_FIX:"):]
        return {"generated_code": code, "human_feedback": None}

    code = _generate_code(plan, query, workspace)
    return {"generated_code": code}


def _generate_code(plan: list[str], query: str, workspace: str) -> str:
    """规则式代码生成器（Week 1 骨架版）。

    TODO: Week1 后用 LLM + coder.md prompt 替换。
    """
    query_lower = query.lower()

    if "eoq" in query_lower or "订货" in query_lower:
        return _generate_eoq_code()

    if "安全库存" in query_lower or "safety" in query_lower:
        return _generate_safety_stock_code()

    if "预测" in query_lower or "forecast" in query_lower:
        return _generate_forecast_code()

    # 默认：生成一个简单的分析脚本
    return textwrap.dedent(f"""\
        #!/usr/bin/env python3
        # Auto-generated by DecisionCoder - {query}

        import sys
        from pathlib import Path

        def main():
            print("=" * 60)
            print("DecisionCoder 执行报告")
            print("=" * 60)
            print()
            print(f"需求: {query}")
            print(f"工作区: {workspace}")
            print()
            print("执行计划:")
            print("-" * 40)
        {''.join(f'    print({chr(34)}{s}{chr(34)})' for s in plan)}

            print()
            print("执行结果: 成功")
            return 0

        if __name__ == "__main__":
            sys.exit(main())
    """)


def _generate_eoq_code() -> str:
    """生成 EOQ 计算代码。"""
    return textwrap.dedent("""\
        #!/usr/bin/env python3
        # Auto-generated by DecisionCoder - EOQ 经济订货批量计算

        import math

        def calculate_eoq(annual_demand: float, ordering_cost: float, holding_cost: float) -> dict:
            eoq = math.sqrt(2 * annual_demand * ordering_cost / holding_cost)
            annual_orders = annual_demand / eoq
            total_cost = (annual_demand / eoq) * ordering_cost + (eoq / 2) * holding_cost
            return {
                "eoq": round(eoq, 2),
                "annual_orders": round(annual_orders, 2),
                "total_cost": round(total_cost, 2),
            }

        def main():
            print("=" * 60)
            print("EOQ 经济订货批量 — 计算结果")
            print("=" * 60)

            # 默认参数（后续从自然语言提取）
            D = 1000   # 年需求量
            S = 50     # 每次订货成本
            H = 2      # 单位持有成本

            result = calculate_eoq(D, S, H)
            print(f"年需求量:     {D} 件")
            print(f"订货成本:     {S} 元/次")
            print(f"持有成本:     {H} 元/(件·年)")
            print(f"---")
            print(f"EOQ:          {result['eoq']} 件")
            print(f"年订货次数:   {result['annual_orders']} 次")
            print(f"年总成本:     {result['total_cost']} 元")
            return 0

        if __name__ == "__main__":
            import sys
            sys.exit(main())
    """)


def _generate_safety_stock_code() -> str:
    """生成安全库存计算代码。"""
    return textwrap.dedent("""\
        #!/usr/bin/env python3
        # Auto-generated by DecisionCoder - 安全库存计算

        from scipy import stats

        def calculate_safety_stock(
            demand_std: float,
            lead_time: float,
            service_level: float = 0.95
        ) -> dict:
            z = stats.norm.ppf(service_level)
            safety_stock = z * demand_std * (lead_time ** 0.5)
            return {
                "z_score": round(z, 3),
                "safety_stock": round(safety_stock, 2),
            }

        def main():
            print("=" * 60)
            print("安全库存 — 计算结果（服务水平法）")
            print("=" * 60)

            # 默认参数
            demand_std = 50    # 需求标准差
            lead_time = 2      # 提前期（周）
            service_level = 0.95  # 95% 服务水平

            result = calculate_safety_stock(demand_std, lead_time, service_level)
            print(f"需求标准差:   {demand_std}")
            print(f"提前期:       {lead_time} 周")
            print(f"服务水平:     {service_level * 100}%")
            print(f"Z值:          {result['z_score']}")
            print(f"安全库存:     {result['safety_stock']} 件")
            return 0

        if __name__ == "__main__":
            import sys
            sys.exit(main())
    """)


def _generate_forecast_code() -> str:
    """生成需求预测代码。"""
    return textwrap.dedent("""\
        #!/usr/bin/env python3
        # Auto-generated by DecisionCoder - 需求预测（移动平均 + 指数平滑）

        import math

        def moving_average(data: list, window: int = 3) -> list:
            result = []
            for i in range(len(data)):
                if i < window - 1:
                    result.append(None)
                else:
                    avg = sum(data[i - window + 1:i + 1]) / window
                    result.append(round(avg, 2))
            return result

        def exponential_smoothing(data: list, alpha: float = 0.3) -> list:
            result = [data[0]]
            for i in range(1, len(data)):
                forecast = alpha * data[i] + (1 - alpha) * result[-1]
                result.append(round(forecast, 2))
            return result

        def main():
            print("=" * 60)
            print("需求预测 — 计算结果")
            print("=" * 60)

            # 示例数据
            demand = [120, 135, 142, 155, 160, 150, 165, 172, 180, 175]

            print(f"历史需求: {demand}")
            print()

            ma = moving_average(demand, window=3)
            print(f"移动平均(窗口=3): {ma}")

            es = exponential_smoothing(demand, alpha=0.3)
            print(f"指数平滑(α=0.3):  {es}")

            print()
            print("建议: 根据近期趋势，下期预测值约为 "
                  f"{es[-1]:.1f}（指数平滑）")
            return 0

        if __name__ == "__main__":
            import sys
            sys.exit(main())
    """)
