#!/usr/bin/env python3
# Auto-generated by DecisionCoder - EOQ 经济订货批量计算

import math

def calculate_eoq(annual_demand: float, ordering_cost: float, holding_cost: float) -> dict:
    eoq = math.sqrt(2 * annual_demand * ordering_cost / holding_cost)
    annual_orders = annual_demand / eoq
    total_cost = (annual_demand / eoq) * ordering_cost + (eoq / 2) * holding_cost
    return {
        "eoq": round(eoq, 2),
        "annual_orders": round(annual_orders, 2),
        "total_cost": round(total_cost, 2),
    }

def main():
    print("=" * 60)
    print("EOQ 经济订货批量 — 计算结果")
    print("=" * 60)

    # 默认参数（后续从自然语言提取）
    D = 1000   # 年需求量
    S = 50     # 每次订货成本
    H = 2      # 单位持有成本

    result = calculate_eoq(D, S, H)
    print(f"年需求量:     {D} 件")
    print(f"订货成本:     {S} 元/次")
    print(f"持有成本:     {H} 元/(件·年)")
    print(f"---")
    print(f"EOQ:          {result['eoq']} 件")
    print(f"年订货次数:   {result['annual_orders']} 次")
    print(f"年总成本:     {result['total_cost']} 元")
    return 0

if __name__ == "__main__":
    import sys
    sys.exit(main())
