"""Coder 节点测试套件。

覆盖场景：
  1. 正常场景 — 验证生成的代码结构安全
  2. 边界场景 — plan 为空 / user_query 为空
  3. 执行验证 — 将生成的代码写入临时文件，用 subprocess 运行
  4. 安全红线 — 验证危险代码被拦截

所有测试数据在脚本内自动生成（创建临时 CSV），不依赖外部文件。
"""

import subprocess
import sys
import tempfile
from pathlib import Path

# 将项目根目录加入 sys.path，确保可以导入 src.agent.nodes.coder
PROJECT_ROOT = Path(__file__).resolve().parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.agent.nodes.coder import run  # coder_node 的别名
from src.agent.nodes.coder import _has_dangerous_code


# ---------------------------------------------------------------------------
# 辅助函数
# ---------------------------------------------------------------------------

def _make_state(
    user_query: str = "",
    plan: list[str] | None = None,
    workspace_path: str | None = None,
    human_feedback: str | None = None,
    retry_count: int = 0,
) -> dict:
    """构造最小 AgentState 字典。"""
    if plan is None:
        plan = []
    if workspace_path is None:
        workspace_path = str(Path(tempfile.gettempdir()) / "dc_test_workspace")

    return {
        "user_query": user_query,
        "workspace_path": workspace_path,
        "plan": plan,
        "generated_code": "",
        "file_path": None,
        "execution_result": None,
        "error": None,
        "retry_count": retry_count,
        "human_feedback": human_feedback,
        "final_report": None,
    }


def _is_syntax_valid(code: str) -> bool:
    """用 compile() 检查代码是否是有效的 Python。"""
    try:
        compile(code, "<test>", "exec")
        return True
    except SyntaxError:
        return False


def _exec_code(code: str, workspace: str) -> subprocess.CompletedProcess:
    """将代码写入临时文件，在给定工作目录下执行。"""
    ws = Path(workspace)
    ws.mkdir(parents=True, exist_ok=True)
    (ws / "data").mkdir(parents=True, exist_ok=True)

    tmp = ws / "_test_exec_temp.py"
    tmp.write_text(code, encoding="utf-8")

    return subprocess.run(
        [sys.executable, str(tmp)],
        capture_output=True,
        text=True,
        timeout=30,
        cwd=str(ws),
    )


def _create_test_csv(workspace: str) -> Path:
    """在工作区 data/ 下创建一个简单的测试 CSV。"""
    data_dir = Path(workspace) / "data"
    data_dir.mkdir(parents=True, exist_ok=True)
    csv = data_dir / "test_sales.csv"
    csv.write_text(
        "date,sku,qty,price\n"
        "2024-01-01,SKU001,10,100\n"
        "2024-01-02,SKU001,15,100\n"
        "2024-01-01,SKU002,8,200\n"
        "2024-01-02,SKU002,12,200\n",
        encoding="utf-8",
    )
    return csv


def _combined(proc: subprocess.CompletedProcess) -> str:
    """安全拼接 stdout 与 stderr。"""
    return (proc.stdout or "") + (proc.stderr or "")


# ---------------------------------------------------------------------------
# 统计
# ---------------------------------------------------------------------------

_passed = 0
_failed = 0
_failures: list[str] = []


def _check(condition: bool, name: str, detail: str = "") -> None:
    global _passed, _failed
    if condition:
        _passed += 1
        print(f"  ✅ {name}")
    else:
        _failed += 1
        _failures.append(f"{name}: {detail}")
        print(f"  ❌ {name}  —  {detail}")


# ===================================================================
# 测试 1 — 正常场景：验证生成代码的结构
# ===================================================================

def test_normal_structure() -> None:
    print("\n[1] 正常场景 — 代码结构检查")

    result = run(_make_state(
        user_query="读取 test_sales.csv 统计每个 sku 的总销量",
        plan=["读取 test_sales.csv 文件", "按 sku 分组统计总销量", "输出统计摘要"],
    ))
    code = result.get("generated_code", "")

    _check(len(code) > 20, "返回非空 generated_code")
    _check("import pandas" in code or "import csv" in code, "包含 import 语句")
    _check("print(" in code, "包含 print() 输出")
    _check("os.system" not in code, "不包含 os.system")
    _check("subprocess" not in code, "不包含 subprocess")
    _check("eval(" not in code, "不包含 eval(")
    _check("exec(" not in code, "不包含 exec(")
    _check("data/" in code, "使用相对路径 data/xxx")
    _check(_is_syntax_valid(code), "语法检查通过 (SyntaxError-free)")

    is_fallback = code.startswith("#!/usr/bin/env python3\n# Auto-generated by DecisionCoder (fallback)")
    _check(not is_fallback, "非回退代码（LLM 正常生成）")


# ===================================================================
# 测试 2 — plan 为空列表
# ===================================================================

def test_edge_empty_plan() -> None:
    print("\n[2] 边界场景 — plan 为空列表")

    ws = str(Path(tempfile.gettempdir()) / "dc_test_empty_plan")
    result = run(_make_state(
        user_query="读取某文件并分析",
        plan=[],
        workspace_path=ws,
    ))
    code = result.get("generated_code", "")

    _check(len(code) > 10, "返回非空 generated_code")
    _check("print(" in code, "包含 print()（不裸奔）")
    _check(_is_syntax_valid(code), "语法检查通过")

    proc = _exec_code(code, ws)
    _check(
        proc.returncode == 0,
        f"运行时正常退出 (returncode={proc.returncode})",
        detail=f"stderr={proc.stderr}",
    )


# ===================================================================
# 测试 3 — user_query 为空
# ===================================================================

def test_edge_empty_query() -> None:
    print("\n[3] 边界场景 — user_query 为空")

    ws = str(Path(tempfile.gettempdir()) / "dc_test_empty_query")
    result = run(_make_state(
        user_query="",
        plan=["读取文件", "分析数据"],
        workspace_path=ws,
    ))
    code = result.get("generated_code", "")

    _check(len(code) > 10, "返回非空 generated_code")
    _check("print(" in code, "包含 print()")
    _check(_is_syntax_valid(code), "语法检查通过")

    proc = _exec_code(code, ws)
    _check(proc.returncode == 0, f"运行时正常退出 (returncode={proc.returncode})")


# ===================================================================
# 测试 4 — 执行验证：数据分析任务
# ===================================================================

def test_execution_data_analysis() -> None:
    """生成代码后实际执行。验证能运行且无 SyntaxError。
    输出精确内容取决于 LLM 生成，不做强约束。"""
    print("\n[4] 执行验证 — 数据分析任务")

    ws = str(Path(tempfile.gettempdir()) / "dc_test_exec_data")
    _create_test_csv(ws)

    result = run(_make_state(
        user_query="读取 test_sales.csv 统计每个 sku 的总销量",
        plan=["读取 test_sales.csv 文件", "按 sku 分组统计总销量", "输出统计摘要"],
        workspace_path=ws,
    ))
    code = result.get("generated_code", "")

    _check(len(code) > 20, f"返回合理长度的代码 ({len(code)} 字符)")
    _check(_is_syntax_valid(code), "语法检查通过")

    proc = _exec_code(code, ws)
    _check(
        proc.returncode == 0,
        f"执行成功 (returncode={proc.returncode})",
        detail=f"stderr={proc.stderr}",
    )
    output = _combined(proc)
    _check(
        any(token in output for token in ("SKU001", "SKU002", "25", "20", "data", "文件", "qty")),
        "输出包含预期关键词",
        detail=f"stdout={proc.stdout[:200]} stderr={proc.stderr[:200]}",
    )


# ===================================================================
# 测试 5 — 执行验证：计算类任务 (EOQ)
# ===================================================================

def test_execution_calculation() -> None:
    """验证计算类代码的正确性。"""
    print("\n[5] 执行验证 — 计算类任务 (EOQ)")

    ws = str(Path(tempfile.gettempdir()) / "dc_test_eoq")

    result = run(_make_state(
        user_query="计算年需求1000件、订货成本50元、持有成本2元的EOQ",
        plan=[
            "设置需求参数 D=1000, S=50, H=2",
            "使用 math.sqrt 计算 EOQ",
            "输出 EOQ 结果",
        ],
        workspace_path=ws,
    ))
    code = result.get("generated_code", "")

    _check(len(code) > 10, f"返回合理长度的代码 ({len(code)} 字符)")
    _check(_is_syntax_valid(code), "语法检查通过")

    proc = _exec_code(code, ws)
    _check(
        proc.returncode == 0,
        f"执行成功 (returncode={proc.returncode})",
        detail=f"stderr={proc.stderr}",
    )
    output = _combined(proc)
    _check(
        "223" in output or "223.6" in output or "eoq" in output.lower() or "EOQ" in output,
        f"输出包含 EOQ 结果",
        detail=f"stdout={proc.stdout[:200]}",
    )


# ===================================================================
# 测试 6 — 执行验证：可视化任务
# ===================================================================

def test_execution_visualization() -> None:
    """验证可视化相关代码结构正确。执行可能因无头环境失败，仅做结构检查。"""
    print("\n[6] 执行验证 — 可视化任务 (matplotlib)")

    ws = str(Path(tempfile.gettempdir()) / "dc_test_viz")
    _create_test_csv(ws)

    result = run(_make_state(
        user_query="读取 test_sales.csv 并画出柱状图",
        plan=["读取 test_sales.csv 文件", "按 sku 分组统计", "绘制柱状图", "保存图片到 reports/"],
        workspace_path=ws,
    ))
    code = result.get("generated_code", "")

    _check(len(code) > 20, f"返回合理长度的代码 ({len(code)} 字符)")
    _check(_is_syntax_valid(code), "语法检查通过")
    _check("import matplotlib" in code or "import pandas" in code,
           "包含 matplotlib 或 pandas import")
    _check("os.system" not in code, "无危险调用")

    # 尝试执行；matplotlib 无头环境可能失败，仅记录
    proc = _exec_code(code, ws)
    if proc.returncode == 0:
        _check(True, "执行成功 (returncode=0)")
    else:
        output = _combined(proc)
        is_headless = "matplotlib" in output.lower() or "backend" in output.lower()
        _check(True, f"执行完成 (returncode={proc.returncode}, headless={is_headless})")


# ===================================================================
# 测试 7 — 安全工具函数
# ===================================================================

def test_safety_helper() -> None:
    print("\n[7] 安全红线 — _has_dangerous_code 辅助函数")

    _check(_has_dangerous_code("import os\nos.system('ls')"), "检测到 os.system")
    _check(_has_dangerous_code("import subprocess\nsubprocess.run(['ls'])"), "检测到 subprocess")
    _check(_has_dangerous_code("eval('1+1')"), "检测到 eval(")
    _check(_has_dangerous_code("exec('x=1')"), "检测到 exec(")
    _check(_has_dangerous_code("__import__('os')"), "检测到 __import__")
    _check(not _has_dangerous_code("import math\nimport pandas as pd\nprint(math.sqrt(4))"),
           "安全代码不误报")


# ===================================================================
# 测试 8 — human_feedback: AI_FIX 透传
# ===================================================================

def test_human_feedback_aifix() -> None:
    print("\n[8] human_feedback — AI_FIX 代码透传")

    result = run(_make_state(
        user_query="读取 sales.csv 统计销量",
        plan=["读取文件", "统计", "输出"],
        human_feedback="AI_FIX:print('fixed code from debugger')",
    ))

    _check(
        result.get("generated_code") == "print('fixed code from debugger')",
        "透传 AI_FIX 后的代码",
    )
    _check(
        result.get("human_feedback") is None,
        "清除 human_feedback 字段",
    )


# ===================================================================
# 测试 9 — human_feedback: SKIP 走正常生成
# ===================================================================

def test_human_feedback_skip() -> None:
    print("\n[9] human_feedback — SKIP 走正常 LLM 生成")

    result = run(_make_state(
        user_query="读取 sales.csv 统计总销量",
        plan=["读取文件", "统计汇总", "输出结果"],
        human_feedback="SKIP",
    ))

    code = result.get("generated_code", "")
    _check(len(code) > 20, "正常生成了代码")
    _check(_is_syntax_valid(code), "语法检查通过")


# ===================================================================
# 测试 10 — plan 中包含"错误"前缀
# ===================================================================

def test_edge_error_plan() -> None:
    """plan 中包含 "错误：xxx" 时触发回退逻辑。"""
    print("\n[10] 边界场景 — plan 包含错误前缀")

    result = run(_make_state(
        user_query="分析数据",
        plan=["错误：API 调用失败"],
    ))
    code = result.get("generated_code", "")

    _check(len(code) > 10, "返回非空回退代码")
    _check("print(" in code, "包含 print()")
    _check(_is_syntax_valid(code), "语法检查通过")
    _check("os.system" not in code, "安全：无危险调用")


# ===================================================================
# 主入口
# ===================================================================

def main() -> int:
    # 加载 .env 中的环境变量（DEEPSEEK_API_KEY）
    from dotenv import load_dotenv
    load_dotenv()

    global _passed, _failed, _failures
    _passed = 0
    _failed = 0
    _failures = []

    print("=" * 60)
    print("Coder 节点测试套件")
    print(f"Python: {sys.version}")
    print("=" * 60)

    test_normal_structure()
    test_edge_empty_plan()
    test_edge_empty_query()
    test_execution_data_analysis()
    test_execution_calculation()
    test_execution_visualization()
    test_safety_helper()
    test_human_feedback_aifix()
    test_human_feedback_skip()
    test_edge_error_plan()

    print("\n" + "=" * 60)
    total = _passed + _failed
    print(f"测试结果: {_passed}/{total} 通过", end="")
    if _failed:
        print(f", {_failed} 失败")
        print("\n失败明细:")
        for f in _failures:
            print(f"  × {f}")
    else:
        print(" — 全部通过 ✅")
    print("=" * 60)

    return 0 if _failed == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
